### PR TITLE
Set gometalinter to run linters sequentially

### PR DESCRIPTION
**Pull request by zcahana**
This PR sets gometalinter to run a single linter at a time, instead of its default of 16 linters concurrently.

On my dev VM, this has improved its runtime duration to ~2:20 (instead of ~4:00), while greatly reducing its memory usage (no more OOMs, no memory leaks).

As a bonus, it prevents gometalinter from producing lint errors (varcheck/aligncheck) on stdlib code:
```
/usr/local/go/src/os/user/lookup.go:38:9:warning: undeclared name: listGroups (aligncheck)
/usr/local/go/src/os/user/lookup.go:9:9:warning: undeclared name: current (aligncheck)
/usr/local/go/src/os/user/lookup.go:15:9:warning: undeclared name: lookupUser (aligncheck)
/usr/local/go/src/os/user/lookup.go:21:9:warning: undeclared name: lookupUserId (aligncheck)
/usr/local/go/src/os/user/lookup.go:27:9:warning: undeclared name: lookupGroup (aligncheck)
/usr/local/go/src/os/user/lookup.go:33:9:warning: undeclared name: lookupGroupId (aligncheck)
```

### CODE REVIEW

**Comment by mandarjog** [comment]
I recently turned the mixer metalinter down to `4` from `16`, it should probably be scaled to the number of cores?  I also added `--enable-gc`.

**Comment by zcahana** [comment]
Ok, I set it to run on 4 cores (hardcoded, but sensible for most machines).
That further reduces the runtime to <2:00 on my VM.

**Comment by zcahana** [comment]
Jenkins build failed due to test infra issue. Waiting for fix in istio/istio-testing#71, then will rebuild this.

**Comment by kyessenov** [comment]
This changes runtime from 10s to 15s on my 16 core, 64GB RAM machine. I'm OK with a bit of slowdown since I think the script is really bounded by one slow linter.

**Pull request merged**
