### PR TITLE
Adds a faster regression suite for manager deps.

### PR DESCRIPTION
**Pull request by sebastienvas**
- No need to run linter and other as code does not change
- Triggering fast forward as last step of POSTSUBMIT stage.

### CODE REVIEW

**Comment by kyessenov** [comment]
presubmit failed with a true bug (possibly envoy). feel free to retry.

**Comment by sebastienvas** [comment]
Thanks. I also noticed that we starting having issue when we upgraded the e2e cluster to 1.6.

**Comment by kyessenov** [comment]
Oh, we're on 1.6 now? Good. My guess is that k8s got faster in sending watcher events, and that is triggering race conditions.

**Comment by sebastienvas** [comment]
Yeah both clusters are on 1.6

**Pull request merged**
