### PR TITLE
Resolve no ingress rule bug

### PR DESCRIPTION
**Pull request by ijsnellf**
Removes `omitempty` from the cluster_manager clusters field. Resolves https://github.com/istio/manager/issues/307

### CODE REVIEW

**Comment by zcahana** [comment]
Fix looks good, but build failed. I couldn't tell what exactly caused the error... any idea?

**Comment by zcahana** [comment]
Btw, would be nice if we can validate (even manually) that this fix indeed produces a valid Envoy configuration (instead of moving to the next error).

**Comment by ijsnellf** [comment]
I am hitting this failure in the check:
```I0322 14:20:03.054801    7798 driver.go:320] kubectl apply -f istio-ingress-ingress-proxy.yaml -n istio-integration-6rg7c
deployment "ingress" created
The Service "ingress" is invalid: spec.ports[0].nodePort: Invalid value: 32443: provided port is already allocated```

This is probably because setting up the node port is a node-wide operation, so it can interfere with other jobs. The tests don't use the node port, so I will remove it.

**Comment by zcahana** [comment]
Do we have concurrent tests running on the same cluster?

**Comment by ijsnellf** [comment]
My understanding was that the tests are run on a gcloud cluster.

**Comment by ijsnellf** [comment]
^^^I did manually verify that this change fixes the bad schema issue when there are no ingress rules.

**Comment by zcahana** [comment]
LGTM, given that the nodePort isn't used in the test. Does it mean that the ingress service is hit from within the cluster, or isn't exercised at all in the test?

**Comment by ijsnellf** [comment]
It is hit from within the cluster: https://github.com/istio/manager/blob/master/test/integration/reachability.go#L298. We are only testing that the Ingress controller is proxying correctly, not that it is exposed externally.

**Pull request merged**
