### PR TITLE
Improve travis pre-submit

### PR DESCRIPTION
**Pull request by kyessenov**
This change is [Reviewable](https://reviewable.io/reviews/istio/manager/50)

### CODE REVIEW

**Comment by sebastienvas** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/istio/manager/50#-KawrznQ9w7Wba74TAdK:-KawrznRAgR15Mu0DuQb:b4jth0i) ([raw file](https://github.com/istio/manager/blob/5d1e8249cd34df0757481346958ba5a008217520/.travis.yml#L30)):*
> ```YAML
>   - export PATH=$PATH:/usr/local/go/bin
>   - sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
>   - sudo apt-get -f install -qqy
> ```

You should not delete this. This will install necessary packages required by the previous dpkg -i

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/manager/50)*

**Comment by kyessenov** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/istio/manager/50#-KawrznQ9w7Wba74TAdK:-Kax540hZAFgzdKjovJK:bso49of) ([raw file](https://github.com/istio/manager/blob/5d1e8249cd34df0757481346958ba5a008217520/.travis.yml#L30)):*
<details><summary><i>Previously, sebastienvas (Sebastien Vas) wrote…</i></summary><blockquote>

You should not delete this. This will install necessary packages required by the previous dpkg -i
</blockquote></details>

Ok. Bazel only needs Java in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/manager/50)*

**Comment by sebastienvas** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/istio/manager/50#-KawrznQ9w7Wba74TAdK:-KaxP2gyomRx2C79XdeZ:bmvo6kh) ([raw file](https://github.com/istio/manager/blob/5d1e8249cd34df0757481346958ba5a008217520/.travis.yml#L30)):*
<details><summary><i>Previously, kyessenov (Kuat) wrote…</i></summary><blockquote>

Ok. Bazel only needs Java in this case.
</blockquote></details>

Not entirely true. According to bazel documentation pkg-config zip g++ zlib1g-dev unzip are also needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/manager/50)*

**Comment by sebastienvas** [comment]
:lgtm:

---

Reviewed 16 of 20 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/manager/50#-:-Kaxgfmu8cn3780erkbu:bnfp4nl)*

**Comment by kyessenov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/istio/manager/50#-KawrznQ9w7Wba74TAdK:-KaxhYT9L1JpreqD8IA1:b-896fix) ([raw file](https://github.com/istio/manager/blob/5d1e8249cd34df0757481346958ba5a008217520/.travis.yml#L30)):*
<details><summary><i>Previously, sebastienvas (Sebastien Vas) wrote…</i></summary><blockquote>

Not entirely true. According to bazel documentation pkg-config zip g++ zlib1g-dev unzip are also needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/istio/manager/50)*

**Pull request merged**
