### PR TITLE
Use newer proxy image

### PR DESCRIPTION
**Pull request by andraxylia**

### CODE REVIEW

**Comment by kyessenov** [comment]
Please investigate what changed in the mixer logs.

**Comment by kyessenov** [comment]
Andra, please revert this back or fix the build. All subsequent PRs will not pass now :(

**Comment by kyessenov** [comment]
As a rule, do not merge PRs until they pass presubmit tests.

**Comment by andraxylia** [comment]
Submitted a PR to revert, not clear from the logs what failed.

**Pull request merged**
