### PR TITLE
Start the informers so the get and list functions work

### PR DESCRIPTION
**Pull request by esnible**
This fixes Issue #653 

The informers weren't being started.

In testing, after the GET operation worked, it returned incorrect output so I fixed that as well.

### CODE REVIEW

**Comment by esnible** [comment]
jenkins rebuild manager/presubmit

**Comment by kyessenov** [comment]
@sebastienvas can we disable bazel caching for now? the problem with non-hermetic genfiles is frustrating. whenever someone changes istio/api protos and updates the files, it pollutes the caches and nothing builds on that node.

**Comment by esnible** [comment]
@kyessenov I created #660 to track the creation of tests for apiserver and istioctl + apiserver.  I could probably create e2e tests for these.  To be more agile I would like to be able to run these tests independent of the other tests.  I didn't see anything like `go test --run <pattern>` for _test/integration/driver.go_.  Am I missing something?  If not may I add it?

**Comment by kyessenov** [comment]
Yes, I just comment out tests i don't need, but using flags to specify which tests to run sounds fine. They are designed to be self-contained now.

**Comment by ayj** [comment]
test/integration/driver.go isn't a proper golang test (yet?). It it were we could restructure sub-tests as separate TestXXX() functions and then you'd be able to use `go test -run TestXXX`.

**Comment by kyessenov** [comment]
Yeah, e2e is a main program, not a go test. I don't know if there is value in converting it to a regular go test (esp. dealing with bazel again), but feel free to do that.

**Comment by esnible** [comment]
jenkins rebuild manager/e2e-smoketest

**Comment by esnible** [comment]
jenkins rebuild manager/e2e-smoketest

**Comment by sebastienvas** [comment]
jenkins rebuild manager/e2e-smoketest

**Comment by sebastienvas** [comment]
jenkins rebuild manager/e2e-smoketest

**Pull request merged**
