### PR TITLE
Run istio containers in priviledged mode

### PR DESCRIPTION
**Pull request by andraxylia**

### CODE REVIEW

**Comment by kyessenov** [comment]
Why privileged mode? We just need it for testing, right?

**Comment by andraxylia** [comment]
There is no guarantee envoy will no longer crash in the future, and while we are still in development mode, it is important to enable core dumps and get our hands on the core files.

**Comment by ayj** [comment]
Do we only need privileged mode to set kernel.core_pattern? If so, can we achieve the result via init-container and modified prepare_proxy.sh (and adding equivalent for non-side car proxy deployments?).

**Comment by kyessenov** [comment]
I don't think we should be using elevated security in our examples (demo or here). A catastrophic failure of Envoy should be dealt with health checking and whole pod termination. Maybe add a debug variable to the template so it's clear that it's purely for debugging.

**Comment by andraxylia** [comment]
Will change prepare_proxy.

**Pull request closed without merging**
